#pragma once

#include <QWidget>
#include "ui_IsoContouringToolbarBase.h" // this file is auto-generated by Qt/CMake

class IsoContouringToolbar : public QWidget, public Ui::IsoContouringToolbarBase
{
    Q_OBJECT
public:
    IsoContouringToolbar(QWidget * parent = nullptr,
            int _max_slices = 100)
        : QWidget(parent)
        , max_slices_(_max_slices)
    {
        setupUi(this);
        n_slices_sb->setMaximum(max_slices_);
        n_slices_slider->setMaximum(max_slices_);
        // slider movement is connected to spinbox, which will emit valueChanged:
        QObject::connect(n_slices_sb, &QSpinBox::valueChanged, this, &IsoContouringToolbar::valueChanged);

        auto link_doublespinbox_and_slider = [this](QSlider *slider, QDoubleSpinBox *spinbox, double n_steps=100.)
        {
            slider->setMinimum(std::lround(spinbox->minimum()*n_steps));
            slider->setMaximum(std::lround(spinbox->maximum()*n_steps));
            slider->setValue(std::lround(spinbox->value()*n_steps));
            connect(spinbox,   &QDoubleSpinBox::valueChanged, [this,slider,n_steps](double v){
                    slider->setSliderPosition(std::lround(v*n_steps));});
            connect(slider,   &QSlider::valueChanged, [this,spinbox,n_steps](int v){
                    spinbox->setValue(v/n_steps);});
        };
        link_doublespinbox_and_slider(offset_slider, offset_dsb);
        QObject::connect(offset_dsb, &QDoubleSpinBox::valueChanged, this, &IsoContouringToolbar::valueChanged);
    }
    int n_slices() const {
        return n_slices_sb->value();
    }
    double offset() const {
        return offset_dsb->value();
    }
signals:
    void valueChanged(int value);


private:
    int max_slices_;
};
