#include "CurveSmoothingPlugin.hh"
#include <Eigen/Sparse>
#include <ObjectTypes/PolyLineCollection/PluginFunctionsPolyLineCollection.hh>
#include <ObjectTypes/PolyLineCollection/PolyLineCollectionObject.hh>
#include <ObjectTypes/PolyLineCollection/PolyLineCollection.hh>
#include <ObjectTypes/PolyLine/PolyLine.hh>
#include <ObjectTypes/PolyMesh/PolyMesh.hh>
#include <ObjectTypes/PolyMesh/PolyMesh.hh>
#include <ObjectTypes/PolyMesh/PolyMeshTypes.hh>
#include <ObjectTypes/PolyMesh/PluginFunctionsPolyMesh.hh>
#include <ObjectTypes/PolyLine/PolyLineObject.hh>
#include <ObjectTypes/PolyLine/PluginFunctionsPolyLine.hh>
#include <ObjectTypes/PolyhedralMesh/PolyhedralMesh.hh>
#include <ObjectTypes/PolyhedralMesh/PluginFunctionsPolyhedralMesh.hh>
#include <random>
#include <limits>

#include "ACG/Math/VectorT.hh"
#include "ui_CurveSmoothingToolbarBase.h" // this file is auto-generated by Qt/CMake

#define ASSIGNMENT_04_SOLUTION 1

using Point = ACG::Vec3d;
using ACG::Vec3d;

static ACG::Vec3d polylineCenter(SimplePolyLine const& line, bool closed)
{
    // TODO: compute a center of mass of the polyline

    closed;

    ACG::Vec3d COM(0.0);
    for (const auto& v : line)
        COM += v;

    return COM / line.size();
};

double polylineMinEdgeLength(SimplePolyLine const& line, bool is_closed)
{
    double shortest_edge = std::numeric_limits<double>::infinity();
    // TODO: compute length of shortest edge

    for (size_t i = 0; i < line.size() - 1; i++)
    {
        double len = (line[i] - line[i+1]).norm();
        if (len < shortest_edge)
            shortest_edge = len;
    }
    if (is_closed)
    {
        double len = (line.front() - line.back()).norm();
        if (len < shortest_edge)
            shortest_edge = len;
    }

    return shortest_edge;
}

double polylineLength(SimplePolyLine const& line, bool is_closed)
{
    double total = 0.;
    // TODO: compute total length of the curve.

    for (size_t i = 0; i < line.size() - 1; i++)
        total += (line[i] - line[i+1]).norm();
    if (is_closed)
        total += (line.front() - line.back()).norm();

    return total;
}

void
CurveSmoothingPlugin::
rescaleCurve(SimplePolyLine &line, bool closed, double target_length)
{
    // TODO: implement rescaling: modify `line` to have
    // target_length, while keeping the same center.
    //
    // Hint: use polylineLength() and polylineCenter()

    double      scaling_factor = target_length / polylineLength(line, closed);
    const auto& COM            = polylineCenter(line, closed);

    for (auto& v : line)
        v = COM + (v - COM) * scaling_factor;
}

void
CurveSmoothingPlugin::
smoothLaplacian(SimplePolyLine const& input, SimplePolyLine &output, bool closed, double eps)
{
    assert (&input != &output);
    int n = input.size();
    for (int i = 0; i < n; ++i) {
        // TODO: Implement uniform Laplacian smoothing:
        //       For each vertex (except for endpoints, if the curve is not closed):
        //          Compute the vector from the vertex towards the average position of its neighbors
        //          Scale this vector by eps.
        //          Move the vertex input[i] along the scaled vector, store the result in output[i]
        //

        if (!closed && (i == 0 || i == n-1)) 
        {
            output[i] = input[i];
            continue;
        }

        const auto& midpoint = (input[(n+i-1)%n] + input[(i+1)%n]) / 2.0;

        output[i] = (1.0 - eps) * input[i] + eps * midpoint;
    }
}


Point compute_circumcenter(const Point& p0, const Point& p1, const Point& p2) {

    // TODO: implement this helper function.
    //       If the points are (approximately) collinear,
    //       it's convenient to just return p1.

    const double D = (p0 - p1).cross(p1 - p2).norm();

    if (D < 1e-10) return p1;
    
    const double alpha = (p1 - p2).dot(p1 - p2) * (p0 - p1).dot(p0 - p2) / (2.0 * D * D);
    const double beta  = (p0 - p2).dot(p0 - p2) * (p1 - p0).dot(p1 - p2) / (2.0 * D * D);
    const double gamma = (p0 - p1).dot(p0 - p1) * (p2 - p0).dot(p2 - p1) / (2.0 * D * D);

    return (alpha * p0 + beta * p1 + gamma * p2);

}

void
CurveSmoothingPlugin::
smoothCurvatureFlow(SimplePolyLine const& input, SimplePolyLine &output, bool closed, double eps)
{
    using Point = ACG::Vec3d;
    const int n = input.size();
    double global_l_min = polylineMinEdgeLength(input, closed);
    double global_dt = (global_l_min * global_l_min);
    //double global_dt = 1.0; // Q: What happens if you use this? Can you choose a good step size?

    for (int i = 0; i < n; ++i) {
        // TODO: Implement curve-shortening flow using (1D mean curvature flow)
        //       For each vertex v (except for endpoints, if the curve is not closed):
        //          - Compute the center c of the discrete osculating circle
        //          - Scale the vector c-v to have the discrete curvature k=1/R as length (Menger curvature)
        //          - move each vertex along this vector, scaled by eps.
        //          - For stability, scale the step with global_dt = l_min^2.
        //              - (You can also experiment with local scaling based on the
        //                 minimum length of incident edges, this has pros and cons)
        //
        //
        if (!closed && (i == 0 || i == n-1)) 
        {
            output[i] = input[i];
            continue;
        }

        const auto&  c = compute_circumcenter(input[(n+i-1)%n], input[i], input[(i+1)%n]);
        const auto&  v = (c - input[i]);
        const auto&  n = v.normalized();
        const double k = 1.0 / (v).norm();

        output[i] = input[i] + eps * global_dt * k * n;
    }
}


class CurveSmoothingToolbar : public QWidget, public Ui::CurveSmoothingToolbarBase
{
    public:
    CurveSmoothingToolbar(QWidget * parent = nullptr)
        : QWidget(parent)
    {
        setupUi(this);
    }
};

void CurveSmoothingPlugin::initializePlugin()
{
    tool_ = new CurveSmoothingToolbar();

    connect(tool_->cb_import_ovm, &QPushButton::clicked, this, &CurveSmoothingPlugin::slotImportOVM);

    // (re-) create curve when curve generation settings are changed or button is pressed:
    connect(tool_->btn_random_curve, &QPushButton::clicked, this, &CurveSmoothingPlugin::slotCreateRandomCurve);
    connect(tool_->sb_npoints, &QSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotCreateRandomCurve); 
    connect(tool_->cb_closed, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotCreateRandomCurve);
    connect(tool_->cb_curve2d, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotCreateRandomCurve);
    connect(tool_->sb_seed, &QSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotCreateRandomCurve);

    // (re-)compute smoothing if any smoothing parameter changes:
    connect(tool_->sb_steps, &QSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->rb_laplacian, &QRadioButton::toggled, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->rb_osc_circle, &QRadioButton::toggled, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->dsb_eps, &QDoubleSpinBox::valueChanged, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->cb_rescale, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotSmooth);
    connect(tool_->cb_vis_intermediate, &QCheckBox::toggled, this, &CurveSmoothingPlugin::slotSmooth);

    emit addToolbox( tr("GP Ex04: Curve Smoothing") , tool_ );
}

PolyLineObject& CurveSmoothingPlugin::getOrCreateCurveObject(int &id, QString const& name, ACG::Vec4f const &color)
{
    if (auto *plo = PluginFunctions::polyLineObject(id)) {
        return *plo;
    } else {
        emit addEmptyObject(DATA_POLY_LINE, id);
        plo = PluginFunctions::polyLineObject(id);
        plo->setName(name);
        plo->materialNode()->set_line_width(5);
        plo->materialNode()->set_point_size(10);
        plo->materialNode()->set_color(color);
        return *plo;
    }
}

PolyLineObject& CurveSmoothingPlugin::getOrCreateInputCurveObject()
{
    auto &obj = getOrCreateCurveObject(input_curve_obj_id_,
            "Input curve", ACG::Vec4f(.5f, .4f, 1.f, 1.f));
    obj.target(true);
    return obj;
}

PolyhedralMeshObject& CurveSmoothingPlugin::getOrCreateOutputMeshObject()
{
    if (auto *pmo = PluginFunctions::polyhedralMeshObject(output_mesh_obj_id_)) {
        return *pmo;
    } else {
        emit addEmptyObject(DATA_POLYHEDRAL_MESH, output_mesh_obj_id_);
        pmo = PluginFunctions::polyhedralMeshObject(output_mesh_obj_id_);
        pmo->setName("Smoothed curve");
        pmo->materialNode()->set_line_width(5);
        pmo->materialNode()->set_point_size(10);
        pmo->materialNode()->set_color(ACG::Vec4f(.9f, .6f, .2f, 1.f));
        pmo->setObjectDrawMode(
                  ACG::SceneGraph::DrawModes::getDrawMode("Edges (wireframe)")
                | ACG::SceneGraph::DrawModes::getDrawMode("Vertices")
                , true);
        return *pmo;
    }
}

PolyhedralMeshObject& CurveSmoothingPlugin::getOrCreateVisualizationMeshObject()
{
    if (auto *pmo = PluginFunctions::polyhedralMeshObject(vis_mesh_obj_id_)) {
        pmo->show(); // this may have been hidden before
        return *pmo;
    } else {
        emit addEmptyObject(DATA_POLYHEDRAL_MESH, vis_mesh_obj_id_);
        pmo = PluginFunctions::polyhedralMeshObject(vis_mesh_obj_id_);
        pmo->setName("Smoothing visualisation");
        pmo->materialNode()->set_line_width(1);
        pmo->materialNode()->set_point_size(1);
        pmo->materialNode()->set_color(ACG::Vec4f{0.3, 0.3, 0.6, 1.0});
        pmo->materialNode()->set_specular_color(ACG::Vec4f{0.5, 0.5, 0.5, 1.0});
        pmo->setObjectDrawMode(
                  ACG::SceneGraph::DrawModes::getDrawMode("Edges (wireframe)")
                | ACG::SceneGraph::DrawModes::getDrawMode("Faces (flat shaded)")
                | ACG::SceneGraph::DrawModes::getDrawMode("Vertices")
                , true);
        return *pmo;
    }
}

void CurveSmoothingPlugin::slotImportOVM()
{
    // Note: You may ignore this function, it's not really related to the point of the exercise.

    for (BaseObjectData * obj: PluginFunctions::objects(
                PluginFunctions::TARGET_OBJECTS,
                DATA_POLYHEDRAL_MESH))
    {
        PolyhedralMeshObject *pmo = PluginFunctions::polyhedralMeshObject(obj);
        PolyhedralMesh const &mesh = *pmo->mesh();
        auto visited = mesh.create_private_vertex_property("visited", false);

        auto line = PolyLine{false};
        int count = 0;
        // simple but inefficient hack to ensure we start enumerating each polyline at
        // one of its end vertices: sort vertices by their valence.
        // This works as long as the input is a collection of polylines,
        // and may or may not do something sensible if we have vertices with valence >=3.
        std::vector<std::pair<int, OpenVolumeMesh::VH>> valence_vh;
        valence_vh.reserve(mesh.n_vertices());
        for (const auto vh: mesh.vertices()) {
            valence_vh.emplace_back(mesh.valence(vh), vh);
        }
        std::sort(valence_vh.begin(), valence_vh.end());

        // Run depth-first search to turn OVM mesh into collection of polylines
        for (const auto& [valence, first_vh] : valence_vh) {
            line.set_closed(false); // we will close it if necessary
            line.clear();
            if (visited[first_vh]) continue;
            auto cur_vh = first_vh;
            auto last_vh = OpenVolumeMesh::VH(-1);

            bool keep_going = true;
            do {
                line.add_point(mesh.vertex(cur_vh));
                visited[cur_vh] = true;
                keep_going = false;
                for (const auto next_vh: mesh.vertex_vertices(cur_vh)) {
                    if (next_vh == last_vh) continue;
                    if (next_vh == first_vh) {
                        line.set_closed(true);
                        break;
                    }
                    if (visited[next_vh]) continue;
                    last_vh = cur_vh;
                    cur_vh = next_vh;
                    keep_going = true;
                    break;
                }
            } while(keep_going);

            if ( (!line.is_closed() && line.n_vertices() < 2)
                || (line.is_closed() && line.n_vertices() < 3))
            {
                continue;
            }

            int obj_id = BaseObject::NOOBJECT;
            auto& curve_obj = getOrCreateCurveObject(obj_id,
                    QString("Imported curve %1").arg(++count),
                    ACG::Vec4f(.5f, .4f, 1.f, 1.f));
            curve_obj.target(true);
            *curve_obj.line() = line;
        }
    }
}

void CurveSmoothingPlugin::slotCreateRandomCurve()
{
    // Note: You may ignore this function, it's not super exciting.
    //       feel free to substitute your own random (or less random)
    //       curve generation. Let us know if you come up with something nicer than this.

    auto &input_curve_obj = getOrCreateInputCurveObject();
    auto &polyline = *input_curve_obj.line();
    polyline.clear();
    polyline.set_closed(tool_->cb_closed->isChecked());

    const bool two_d = tool_->cb_curve2d->isChecked();
    const int n_points = tool_->sb_npoints->value();

    int seed = tool_->sb_seed->value();
    std::default_random_engine gen(seed);
    std::normal_distribution<double> noise_dist(0., 1. / (n_points+3));
    std::uniform_real_distribution<double> phase_dist(0., 2*M_PI);

    constexpr int n_octaves = 10;
    std::array<double, n_octaves> phases;
    for (int i = 0; i < n_octaves; ++i) {
        phases[i] = phase_dist(gen);
    }
    for (int k = 0; k < n_points; ++k) {
        const double phi = 2 * M_PI * (k + .5) / n_points;
        Point p{0.};
        double freq = 1.;
        for (int i = 1; i <= n_octaves; ++i) {
            auto w = 1. / (i*i);
            auto phase = phases[i-1];
            p[0] += w * sin(freq * phi + phase);
            p[1] += w * cos(freq * phi + phase);
            if (!two_d) { p[2] += w * sin(2 * freq * phi + phase); }
            freq *= 2;
        }
        if (0) {
            p[0] += noise_dist(gen);
            p[1] += noise_dist(gen);
            if (!two_d) { p[2] += noise_dist(gen); }
        }
        polyline.add_point(p);
    }
    slotSmooth();
    emit updatedObject(input_curve_obj.id(), UPDATE_ALL);
}


void CurveSmoothingPlugin::smoothCurve(
        PolyLine input, PolyhedralMesh *out_mesh, PolyhedralMesh *vis_mesh)
{
    const int n_steps = tool_->sb_steps->value();
    CurveSmoothingMethod method;
    if (tool_->rb_laplacian->isChecked()) {
        method = CurveSmoothingMethod::UniformLaplacian;
    } else {
        assert(tool_->rb_osc_circle->isChecked());
        method = CurveSmoothingMethod::OsculatingCircle;
    }
    const double eps = tool_->dsb_eps->value();

    /// Copy a given polyline into a OVM mesh, return vector of edge handles
    auto add_polyline_to_ovm = [](PolyhedralMesh &mesh, PolyLine const& line)
        -> std::vector<OpenVolumeMesh::EdgeHandle>
    {
        std::vector<OpenVolumeMesh::EdgeHandle> edges; edges.reserve(line.n_edges());
        int first_new_vh = mesh.n_vertices();
        auto last_vh = OpenVolumeMesh::VertexHandle(-1);
        for (auto &p: line.points()) {
            auto vh = mesh.add_vertex(p);
            if (last_vh.is_valid()) {
                auto eh = mesh.add_edge(last_vh, vh);
                edges.push_back(eh);
            }
            last_vh = vh;
        }
        if (line.is_closed()) {
            auto eh = mesh.add_edge(last_vh, OpenVolumeMesh::VertexHandle(first_new_vh));
            edges.push_back(eh);
        }
        return edges;
    };

    /// helper for visualizing smoothing trajectories
    auto add_quad_strip_to_ovm = [] (
        PolyhedralMesh &mesh,
        std::vector<OpenVolumeMesh::EdgeHandle> const &last,
        std::vector<OpenVolumeMesh::EdgeHandle> const &cur)
    {
        assert(cur.size() == last.size());
        int n = last.size();
        for (int i = 0; i < n; ++i) {
            mesh.add_face({
                mesh.edge(last[i]).from_vertex(),
                mesh.edge(last[i]).to_vertex(),
                mesh.edge(cur[i]).to_vertex(),
                mesh.edge(cur[i]).from_vertex()
                });
        }
    };
    std::vector<OpenVolumeMesh::EdgeHandle> ovm_edges;

    PolyLine output;
    output.set_closed(input.is_closed());
    output.resize(input.n_vertices());
    if (vis_mesh) {
        ovm_edges = add_polyline_to_ovm(*vis_mesh, input);
    }
    double totalLength = polylineLength(input.points(), input.is_closed());
    for (int i = 0; i < n_steps; ++i) {
        switch (method) {
            case CurveSmoothingMethod::UniformLaplacian:
                smoothLaplacian(input.points(), output.points(), input.is_closed(), eps);
                break;
            case CurveSmoothingMethod::OsculatingCircle:
                smoothCurvatureFlow(input.points(), output.points(), input.is_closed(), eps);
                break;
        }

        if (tool_->cb_rescale->isChecked()) {
            rescaleCurve(output.points(), input.is_closed(), totalLength);
        }

        if (vis_mesh) {
            auto edges = add_polyline_to_ovm(*vis_mesh, output);
            if (!ovm_edges.empty()) {
                add_quad_strip_to_ovm(*vis_mesh, ovm_edges, edges);
            }
            ovm_edges = edges;
        }
        // Use output as input for the next iteration:
        std::swap(input, output);
    }
    if (n_steps > 0) {
        // The last iteration has swapped input and output, so "input" contains the final result:
        add_polyline_to_ovm(*out_mesh, input);
    }
}

void CurveSmoothingPlugin::slotSmooth()
{

    PolyhedralMesh *vis_mesh = nullptr;
    if (tool_->cb_vis_intermediate->isChecked()) {
        auto &pmo = getOrCreateVisualizationMeshObject();
        vis_mesh = pmo.mesh();
        vis_mesh->clear(false);
    } else {
        auto *pmo = PluginFunctions::polyhedralMeshObject(vis_mesh_obj_id_);
        if (pmo) pmo->hide();
    }

    auto &output_obj = getOrCreateOutputMeshObject();
    output_obj.mesh()->clear(false);


    for (BaseObjectData * obj: PluginFunctions::objects(
                PluginFunctions::TARGET_OBJECTS,
                DATA_POLY_LINE))
    {
        auto *input = PluginFunctions::polyLineObject(obj->id())->line();
        if (input->n_vertices() < 2) { return; }
        smoothCurve(*input, output_obj.mesh(), vis_mesh);
    }

    emit updatedObject(output_obj.id(), UPDATE_ALL);
    if (vis_mesh) {
        emit updatedObject(vis_mesh_obj_id_, UPDATE_ALL);
    }

}

