#include "GPHelloEigenPlugin.hh"
#include <Eigen/Sparse>

#include "ui_GPHelloEigenToolbarBase.h" // this file is auto-generated by Qt/CMake

class GPHelloEigenToolbar : public QWidget, public Ui::GPHelloEigenToolbarBase
{
    public:
    GPHelloEigenToolbar(QWidget * parent = nullptr)
        : QWidget(parent)
    {
        setupUi(this);
    }
};

void GPHelloEigenPlugin::initializePlugin()
{
    tool_ = new GPHelloEigenToolbar();
    connect(tool_->hello_eigen, &QPushButton::clicked, this, &GPHelloEigenPlugin::slotHelloEigen);
    emit addToolbox( tr("GP Ex01: Hello Eigen") , tool_ );
}

void GPHelloEigenPlugin::slotHelloEigen()
{
    using SMatd = Eigen::SparseMatrix<double>;
    using T = Eigen::Triplet<double>;
    using VecXd = Eigen::VectorXd;


    auto A = SMatd(5, 5);
    auto b = VecXd(5);
    b << 8, 45, -3, 3, 19;

    auto x = VecXd(5);


    // TODO: solve the following fixed sparse linear system Ax = b:
    //
    //     [ 2  3  0  0  0 ]       [  8]
    //     [ 3  0  4  0  6 ]       [ 20]
    //     [ 0 -1 -3 -2  0 ] * x = [ 13]
    //     [ 0  0  1  0  0 ]       [  6]
    //     [ 0  2  4  0  1 ]       [ 17]
    //
    // Read the documentation of Eigen on sparse linear
    // algebra <https://libeigen.gitlab.io/eigen/docs-nightly/group__TutorialSparse.html>.
    // Solve the system and ensure the solution is correct.


    // --- code begin --- //

    std::vector<T> triplets;

    triplets.push_back(T(0, 0, 2));
    triplets.push_back(T(1, 0, 3));
    triplets.push_back(T(0, 1, 3));
    triplets.push_back(T(2, 1, -1));
    triplets.push_back(T(4, 1, 2));
    triplets.push_back(T(1, 2, 4));
    triplets.push_back(T(2, 2, -3));
    triplets.push_back(T(3, 2, 1));
    triplets.push_back(T(4, 2, 4));
    triplets.push_back(T(2, 3, -2));
    triplets.push_back(T(1, 4, 6));
    triplets.push_back(T(4, 4, 1));
    A.setFromTriplets(triplets.begin(), triplets.end());

    Eigen::SparseLU<SMatd> solver;
    solver.compute(A);
    x = solver.solve(b);

    // ---  code end  --- //


    std::cout<<"Linear system Ax = b. \nA is:\n"<<A<<std::endl;
    std::cout<<"b is:\n"<<b<<std::endl;
    std::cout<<"x is:\n"<<x<<std::endl;

    double err = (A*x - b).lpNorm<2>();
    if (err < 1e-8) {
        emit log(LOGINFO, "Solution verified, error = " + QString::number(err));
    } else {
        emit log(LOGERR, "Error: wrong solution, error = " + QString::number(err));
    }
}

